Add build scripts and README file for Derecho
NCAR/tuv-x pull request #11
Opened 2023-10-16 22:38 UTC by sjsprecious

This PR introduces the build scripts and README file about how to build TUV-x and its dependencies on Derecho.

The scripts work for both GNU and Intel compilers (both of them compile successfully).

- Using the GNU compiler, all the 59 regression tests are passed.
- Using the Intel compiler, the regression test suite hangs at the regression_aerosols_radiator_4strm test for an unknown reason (https://github.com/NCAR/tuv-x-private/issues/286).

2023-10-16 22:48 UTC, mattldawson requested changes
looks great! just a couple minor changes for the new tuv-x repo

2023-10-16 22:48 UTC, mattldawson commented on etc/derecho/README.md
> +cd $TUVX_HOME/tuv-x-private/build
```suggestion
cd $TUVX_HOME/tuv-x/build
```

2023-10-16 22:48 UTC, mattldawson commented on etc/derecho/README.md
> +cd $TUVX_HOME/tuv-x-private/build
```suggestion
cd $TUVX_HOME/tuv-x/build
```

2023-10-16 22:48 UTC, mattldawson commented on etc/derecho/build_tuvx_derecho_gnu.sh
> +cd tuv-x-private
```suggestion
git clone git@github.com:NCAR/tuv-x.git
cd tuv-x
```

2023-10-16 22:48 UTC, mattldawson commented on etc/derecho/build_tuvx_derecho_intel.sh
> +cd tuv-x-private
```suggestion
git clone git@github.com:NCAR/tuv-x.git
cd tuv-x
```

2023-10-16 22:51 UTC, sjsprecious commented on etc/derecho/README.md
> +cd $TUVX_HOME/tuv-x-private/build
Thanks for catching it!

2023-10-17 14:14 UTC, K20shores approved these changes

2023-10-18 21:54 UTC, mattldawson approved these changes

2023-10-18 21:54 UTC, merged