add grid to profile from csv config
NCAR/tuv-x pull request #138
Opened 2022-08-19 20:54 UTC by mattldawson

closes #137 

the updated documentation can be found [here](https://ncar.github.io/tuv-x/branch/develop-137-config-profile-grid/configuration/#configuration-profiles-from-csv)

2022-08-20 16:42 UTC, K20shores requested changes

2022-08-20 16:42 UTC, K20shores commented on src/profiles/from_csv_file.F90
> +    this%layer_dens_ = this%mid_val_ * grid%delta_ * km2cm
The only grid allowed would have to be a grid in kilometers because of this conversion. We either need to rethink how `layer_dens_` is defined, or document that this profile needs a grid to be in kilometers and make an assert for the units in this constructor.

2022-08-22 13:57 UTC, K20shores commented
Does this also close #123?

2022-08-22 15:26 UTC, mattldawson commented on src/profiles/from_csv_file.F90
> +    this%layer_dens_ = this%mid_val_ * grid%delta_ * km2cm
ah, good point - I missed that. Not sure the best way to solve this. I think these layer densities only make sense for vertical profiles. I don't like to bake special treatments into what is supposed to be a general type like this, but the only general solutions I can think of are to adopt SI units throughout (my preference) or to build in unit conversions (more complicated than necessary, imo). For now, I can put a check around this to do this conversion if the grid is `height` in `km` and then create a separate issue for adopting SI units. What do you think?

2022-08-22 15:27 UTC, K20shores commented on src/profiles/from_csv_file.F90
> +    this%layer_dens_ = this%mid_val_ * grid%delta_ * km2cm
Yes, I like that.

2022-08-22 16:27 UTC, mattldawson commented
> Does this also close #123?

I closed that one as a duplicate

2022-08-22 19:24 UTC, K20shores approved these changes

2022-08-22 19:24 UTC, merged