211 restructure configuration format
NCAR/tuv-x pull request #233
Opened 2022-12-14 22:31 UTC by K20shores

2022-12-14 23:12 UTC, K20shores commented on src/profile_warehouse.F90
> -      deallocate( temp_profiles )
@mattldawson I don't know if there was a reason we had for making the profiles and copying the pointers as the array grew, but I removed. I did have to add line 249 below in the `profile_warehouse%exists` function, not sure if that's appropriate or not

2022-12-15 18:45 UTC, mattldawson commented on src/profile_warehouse.F90
> +    integer                        :: profile_idx = 1
this is another really strange fortran thing. If you define a variable when you declare it, fortran makes it static. I have no idea why. I would just remove the `= 1` here and set it to 1 before you enter the loop.

2022-12-15 18:47 UTC, mattldawson commented on src/profile_warehouse.F90
> -      deallocate( temp_profiles )
yeah, I like your way better.

2022-12-15 20:49 UTC, mattldawson requested changes
looks good! just a very minor doc change, and one array size change

2022-12-15 20:49 UTC, mattldawson commented on src/profiles/from_csv_file.F90
> +    type(string_t) :: required_keys(5), optional_keys(4)
```suggestion
    type(string_t) :: required_keys(5), optional_keys(2)
```

2022-12-15 20:49 UTC, mattldawson commented on docs/source/user_guide.rst
> +, ``units``, and name.
```suggestion
, ``units``, and ``name``.
```

2022-12-15 21:24 UTC, mattldawson approved these changes

2022-12-15 21:52 UTC, merged